apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "raven.labels" . | nindent 4 }}
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "raven.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.secrets.grafanaPassword | default "" | quote }}
