// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: monitor/v1/monitor.proto

package monitorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_CreateMonitor_FullMethodName      = "/monitor.v1.MonitorService/CreateMonitor"
	MonitorService_GetMonitor_FullMethodName         = "/monitor.v1.MonitorService/GetMonitor"
	MonitorService_UpdateMonitor_FullMethodName      = "/monitor.v1.MonitorService/UpdateMonitor"
	MonitorService_DeleteMonitor_FullMethodName      = "/monitor.v1.MonitorService/DeleteMonitor"
	MonitorService_ListMonitorsByUser_FullMethodName = "/monitor.v1.MonitorService/ListMonitorsByUser"
	MonitorService_GetMonitorStatus_FullMethodName   = "/monitor.v1.MonitorService/GetMonitorStatus"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorServiceClient interface {
	CreateMonitor(ctx context.Context, in *CreateMonitorRequest, opts ...grpc.CallOption) (*CreateMonitorResponse, error)
	GetMonitor(ctx context.Context, in *GetMonitorRequest, opts ...grpc.CallOption) (*GetMonitorResponse, error)
	UpdateMonitor(ctx context.Context, in *UpdateMonitorRequest, opts ...grpc.CallOption) (*UpdateMonitorResponse, error)
	DeleteMonitor(ctx context.Context, in *DeleteMonitorRequest, opts ...grpc.CallOption) (*DeleteMonitorResponse, error)
	ListMonitorsByUser(ctx context.Context, in *ListMonitorsByUserRequest, opts ...grpc.CallOption) (*ListMonitorsByUserResponse, error)
	GetMonitorStatus(ctx context.Context, in *GetMonitorStatusRequest, opts ...grpc.CallOption) (*GetMonitorStatusResponse, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) CreateMonitor(ctx context.Context, in *CreateMonitorRequest, opts ...grpc.CallOption) (*CreateMonitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMonitorResponse)
	err := c.cc.Invoke(ctx, MonitorService_CreateMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMonitor(ctx context.Context, in *GetMonitorRequest, opts ...grpc.CallOption) (*GetMonitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonitorResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) UpdateMonitor(ctx context.Context, in *UpdateMonitorRequest, opts ...grpc.CallOption) (*UpdateMonitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMonitorResponse)
	err := c.cc.Invoke(ctx, MonitorService_UpdateMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) DeleteMonitor(ctx context.Context, in *DeleteMonitorRequest, opts ...grpc.CallOption) (*DeleteMonitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMonitorResponse)
	err := c.cc.Invoke(ctx, MonitorService_DeleteMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListMonitorsByUser(ctx context.Context, in *ListMonitorsByUserRequest, opts ...grpc.CallOption) (*ListMonitorsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMonitorsByUserResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListMonitorsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMonitorStatus(ctx context.Context, in *GetMonitorStatusRequest, opts ...grpc.CallOption) (*GetMonitorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonitorStatusResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetMonitorStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility.
type MonitorServiceServer interface {
	CreateMonitor(context.Context, *CreateMonitorRequest) (*CreateMonitorResponse, error)
	GetMonitor(context.Context, *GetMonitorRequest) (*GetMonitorResponse, error)
	UpdateMonitor(context.Context, *UpdateMonitorRequest) (*UpdateMonitorResponse, error)
	DeleteMonitor(context.Context, *DeleteMonitorRequest) (*DeleteMonitorResponse, error)
	ListMonitorsByUser(context.Context, *ListMonitorsByUserRequest) (*ListMonitorsByUserResponse, error)
	GetMonitorStatus(context.Context, *GetMonitorStatusRequest) (*GetMonitorStatusResponse, error)
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) CreateMonitor(context.Context, *CreateMonitorRequest) (*CreateMonitorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) GetMonitor(context.Context, *GetMonitorRequest) (*GetMonitorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) UpdateMonitor(context.Context, *UpdateMonitorRequest) (*UpdateMonitorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) DeleteMonitor(context.Context, *DeleteMonitorRequest) (*DeleteMonitorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) ListMonitorsByUser(context.Context, *ListMonitorsByUserRequest) (*ListMonitorsByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMonitorsByUser not implemented")
}
func (UnimplementedMonitorServiceServer) GetMonitorStatus(context.Context, *GetMonitorStatusRequest) (*GetMonitorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonitorStatus not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call panics, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_CreateMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).CreateMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_CreateMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).CreateMonitor(ctx, req.(*CreateMonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMonitor(ctx, req.(*GetMonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_UpdateMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).UpdateMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_UpdateMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).UpdateMonitor(ctx, req.(*UpdateMonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_DeleteMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).DeleteMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_DeleteMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).DeleteMonitor(ctx, req.(*DeleteMonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListMonitorsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMonitorsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListMonitorsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListMonitorsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListMonitorsByUser(ctx, req.(*ListMonitorsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMonitorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonitorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMonitorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMonitorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMonitorStatus(ctx, req.(*GetMonitorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.v1.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMonitor",
			Handler:    _MonitorService_CreateMonitor_Handler,
		},
		{
			MethodName: "GetMonitor",
			Handler:    _MonitorService_GetMonitor_Handler,
		},
		{
			MethodName: "UpdateMonitor",
			Handler:    _MonitorService_UpdateMonitor_Handler,
		},
		{
			MethodName: "DeleteMonitor",
			Handler:    _MonitorService_DeleteMonitor_Handler,
		},
		{
			MethodName: "ListMonitorsByUser",
			Handler:    _MonitorService_ListMonitorsByUser_Handler,
		},
		{
			MethodName: "GetMonitorStatus",
			Handler:    _MonitorService_GetMonitorStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/v1/monitor.proto",
}
