// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: monitor/v1/monitor.proto

package monitorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Monitor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Target          string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,5,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	UserId          string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel         string                 `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	LastStatus      string                 `protobuf:"bytes,9,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"`
	LastCheckedAt   string                 `protobuf:"bytes,10,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Monitor) Reset() {
	*x = Monitor{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitor) ProtoMessage() {}

func (x *Monitor) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitor.ProtoReflect.Descriptor instead.
func (*Monitor) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Monitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Monitor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Monitor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Monitor) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Monitor) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *Monitor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Monitor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Monitor) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Monitor) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *Monitor) GetLastCheckedAt() string {
	if x != nil {
		return x.LastCheckedAt
	}
	return ""
}

type CreateMonitorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Target          string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	UserId          string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel         string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMonitorRequest) Reset() {
	*x = CreateMonitorRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorRequest) ProtoMessage() {}

func (x *CreateMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorRequest.ProtoReflect.Descriptor instead.
func (*CreateMonitorRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMonitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMonitorRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateMonitorRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateMonitorRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *CreateMonitorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMonitorRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CreateMonitorRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitor       *Monitor               `protobuf:"bytes,1,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMonitorResponse) Reset() {
	*x = CreateMonitorResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorResponse) ProtoMessage() {}

func (x *CreateMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorResponse.ProtoReflect.Descriptor instead.
func (*CreateMonitorResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMonitorResponse) GetMonitor() *Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

type GetMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorRequest) Reset() {
	*x = GetMonitorRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorRequest) ProtoMessage() {}

func (x *GetMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorRequest.ProtoReflect.Descriptor instead.
func (*GetMonitorRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *GetMonitorRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

type GetMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitor       *Monitor               `protobuf:"bytes,1,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorResponse) Reset() {
	*x = GetMonitorResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorResponse) ProtoMessage() {}

func (x *GetMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorResponse.ProtoReflect.Descriptor instead.
func (*GetMonitorResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *GetMonitorResponse) GetMonitor() *Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

type UpdateMonitorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MonitorId       string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateMonitorRequest) Reset() {
	*x = UpdateMonitorRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonitorRequest) ProtoMessage() {}

func (x *UpdateMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonitorRequest.ProtoReflect.Descriptor instead.
func (*UpdateMonitorRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMonitorRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *UpdateMonitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMonitorRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type UpdateMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitor       *Monitor               `protobuf:"bytes,1,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMonitorResponse) Reset() {
	*x = UpdateMonitorResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonitorResponse) ProtoMessage() {}

func (x *UpdateMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonitorResponse.ProtoReflect.Descriptor instead.
func (*UpdateMonitorResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMonitorResponse) GetMonitor() *Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

type DeleteMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMonitorRequest) Reset() {
	*x = DeleteMonitorRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorRequest) ProtoMessage() {}

func (x *DeleteMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorRequest.ProtoReflect.Descriptor instead.
func (*DeleteMonitorRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMonitorRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

type DeleteMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMonitorResponse) Reset() {
	*x = DeleteMonitorResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorResponse) ProtoMessage() {}

func (x *DeleteMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorResponse.ProtoReflect.Descriptor instead.
func (*DeleteMonitorResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMonitorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListMonitorsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorsByUserRequest) Reset() {
	*x = ListMonitorsByUserRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorsByUserRequest) ProtoMessage() {}

func (x *ListMonitorsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListMonitorsByUserRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *ListMonitorsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMonitorsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMonitorsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitors      []*Monitor             `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorsByUserResponse) Reset() {
	*x = ListMonitorsByUserResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorsByUserResponse) ProtoMessage() {}

func (x *ListMonitorsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorsByUserResponse.ProtoReflect.Descriptor instead.
func (*ListMonitorsByUserResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *ListMonitorsByUserResponse) GetMonitors() []*Monitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

type GetMonitorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorStatusRequest) Reset() {
	*x = GetMonitorStatusRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorStatusRequest) ProtoMessage() {}

func (x *GetMonitorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMonitorStatusRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *GetMonitorStatusRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

type GetMonitorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LastCheck     string                 `protobuf:"bytes,2,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	Up            bool                   `protobuf:"varint,3,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorStatusResponse) Reset() {
	*x = GetMonitorStatusResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorStatusResponse) ProtoMessage() {}

func (x *GetMonitorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMonitorStatusResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *GetMonitorStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMonitorStatusResponse) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

func (x *GetMonitorStatusResponse) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

var File_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x18monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\"\x98\x02\n" +
	"\aMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12)\n" +
	"\x10interval_seconds\x18\x05 \x01(\x05R\x0fintervalSeconds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12\x1f\n" +
	"\vlast_status\x18\t \x01(\tR\n" +
	"lastStatus\x12&\n" +
	"\x0flast_checked_at\x18\n" +
	" \x01(\tR\rlastCheckedAt\"\xdd\x01\n" +
	"\x14CreateMonitorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"F\n" +
	"\x15CreateMonitorResponse\x12-\n" +
	"\amonitor\x18\x01 \x01(\v2\x13.monitor.v1.MonitorR\amonitor\"2\n" +
	"\x11GetMonitorRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"C\n" +
	"\x12GetMonitorResponse\x12-\n" +
	"\amonitor\x18\x01 \x01(\v2\x13.monitor.v1.MonitorR\amonitor\"t\n" +
	"\x14UpdateMonitorRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\"F\n" +
	"\x15UpdateMonitorResponse\x12-\n" +
	"\amonitor\x18\x01 \x01(\v2\x13.monitor.v1.MonitorR\amonitor\"5\n" +
	"\x14DeleteMonitorRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"'\n" +
	"\x15DeleteMonitorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"J\n" +
	"\x19ListMonitorsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x1aListMonitorsByUserResponse\x12/\n" +
	"\bmonitors\x18\x01 \x03(\v2\x13.monitor.v1.MonitorR\bmonitors\"8\n" +
	"\x17GetMonitorStatusRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"a\n" +
	"\x18GetMonitorStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"last_check\x18\x02 \x01(\tR\tlastCheck\x12\x0e\n" +
	"\x02up\x18\x03 \x01(\bR\x02up2\xa3\x04\n" +
	"\x0eMonitorService\x12T\n" +
	"\rCreateMonitor\x12 .monitor.v1.CreateMonitorRequest\x1a!.monitor.v1.CreateMonitorResponse\x12K\n" +
	"\n" +
	"GetMonitor\x12\x1d.monitor.v1.GetMonitorRequest\x1a\x1e.monitor.v1.GetMonitorResponse\x12T\n" +
	"\rUpdateMonitor\x12 .monitor.v1.UpdateMonitorRequest\x1a!.monitor.v1.UpdateMonitorResponse\x12T\n" +
	"\rDeleteMonitor\x12 .monitor.v1.DeleteMonitorRequest\x1a!.monitor.v1.DeleteMonitorResponse\x12c\n" +
	"\x12ListMonitorsByUser\x12%.monitor.v1.ListMonitorsByUserRequest\x1a&.monitor.v1.ListMonitorsByUserResponse\x12]\n" +
	"\x10GetMonitorStatus\x12#.monitor.v1.GetMonitorStatusRequest\x1a$.monitor.v1.GetMonitorStatusResponseB=Z;github.com/ssrjkk/raven/services/proto/monitor/v1;monitorv1b\x06proto3"

var (
	file_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_monitor_v1_monitor_proto_rawDescData []byte
)

func file_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_monitor_v1_monitor_proto_rawDescData
}

var file_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_monitor_v1_monitor_proto_goTypes = []any{
	(*Monitor)(nil),                    // 0: monitor.v1.Monitor
	(*CreateMonitorRequest)(nil),       // 1: monitor.v1.CreateMonitorRequest
	(*CreateMonitorResponse)(nil),      // 2: monitor.v1.CreateMonitorResponse
	(*GetMonitorRequest)(nil),          // 3: monitor.v1.GetMonitorRequest
	(*GetMonitorResponse)(nil),         // 4: monitor.v1.GetMonitorResponse
	(*UpdateMonitorRequest)(nil),       // 5: monitor.v1.UpdateMonitorRequest
	(*UpdateMonitorResponse)(nil),      // 6: monitor.v1.UpdateMonitorResponse
	(*DeleteMonitorRequest)(nil),       // 7: monitor.v1.DeleteMonitorRequest
	(*DeleteMonitorResponse)(nil),      // 8: monitor.v1.DeleteMonitorResponse
	(*ListMonitorsByUserRequest)(nil),  // 9: monitor.v1.ListMonitorsByUserRequest
	(*ListMonitorsByUserResponse)(nil), // 10: monitor.v1.ListMonitorsByUserResponse
	(*GetMonitorStatusRequest)(nil),    // 11: monitor.v1.GetMonitorStatusRequest
	(*GetMonitorStatusResponse)(nil),   // 12: monitor.v1.GetMonitorStatusResponse
}
var file_monitor_v1_monitor_proto_depIdxs = []int32{
	0,  // 0: monitor.v1.CreateMonitorResponse.monitor:type_name -> monitor.v1.Monitor
	0,  // 1: monitor.v1.GetMonitorResponse.monitor:type_name -> monitor.v1.Monitor
	0,  // 2: monitor.v1.UpdateMonitorResponse.monitor:type_name -> monitor.v1.Monitor
	0,  // 3: monitor.v1.ListMonitorsByUserResponse.monitors:type_name -> monitor.v1.Monitor
	1,  // 4: monitor.v1.MonitorService.CreateMonitor:input_type -> monitor.v1.CreateMonitorRequest
	3,  // 5: monitor.v1.MonitorService.GetMonitor:input_type -> monitor.v1.GetMonitorRequest
	5,  // 6: monitor.v1.MonitorService.UpdateMonitor:input_type -> monitor.v1.UpdateMonitorRequest
	7,  // 7: monitor.v1.MonitorService.DeleteMonitor:input_type -> monitor.v1.DeleteMonitorRequest
	9,  // 8: monitor.v1.MonitorService.ListMonitorsByUser:input_type -> monitor.v1.ListMonitorsByUserRequest
	11, // 9: monitor.v1.MonitorService.GetMonitorStatus:input_type -> monitor.v1.GetMonitorStatusRequest
	2,  // 10: monitor.v1.MonitorService.CreateMonitor:output_type -> monitor.v1.CreateMonitorResponse
	4,  // 11: monitor.v1.MonitorService.GetMonitor:output_type -> monitor.v1.GetMonitorResponse
	6,  // 12: monitor.v1.MonitorService.UpdateMonitor:output_type -> monitor.v1.UpdateMonitorResponse
	8,  // 13: monitor.v1.MonitorService.DeleteMonitor:output_type -> monitor.v1.DeleteMonitorResponse
	10, // 14: monitor.v1.MonitorService.ListMonitorsByUser:output_type -> monitor.v1.ListMonitorsByUserResponse
	12, // 15: monitor.v1.MonitorService.GetMonitorStatus:output_type -> monitor.v1.GetMonitorStatusResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_monitor_v1_monitor_proto_init() }
func file_monitor_v1_monitor_proto_init() {
	if File_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_v1_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_monitor_v1_monitor_proto = out.File
	file_monitor_v1_monitor_proto_goTypes = nil
	file_monitor_v1_monitor_proto_depIdxs = nil
}
