# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Raven AI Windows executable.

Usage:
    pyinstaller build/raven.spec

To replace the mascot icon:
    1. Place your .ico file at resources/raven.ico
    2. Update the `icon` parameter below
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent

a = Analysis(
    [str(ROOT / "raven" / "__main__.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / "raven" / "plugins"), "raven/plugins"),
        (str(ROOT / "workspace"), "workspace"),
        (str(ROOT / "plugins"), "plugins"),
    ],
    hiddenimports=[
        # Core modules
        "raven",
        "raven.core",
        "raven.core.config",
        "raven.core.db",
        "raven.core.models",
        "raven.core.llm",
        "raven.core.plugin_loader",
        "raven.core.task_queue",
        "raven.core.agent",
        "raven.core.agent.agent",
        "raven.core.agent.registry",
        "raven.core.gateway",
        "raven.core.gateway.gateway",
        "raven.core.plugins",
        "raven.core.channels",
        "raven.core.sse",
        "raven.core.tracing",
        "raven.core.audit",
        "raven.core.health",
        "raven.core.metrics",
        "raven.core.middleware",
        "raven.core.admin_api",
        "raven.core.secrets",
        "raven.core.config_store",
        "raven.core.config_watcher",
        "raven.core.failover",
        "raven.core.sandbox",
        "raven.core.skills",
        "raven.core.http_client",
        "raven.core.logging",
        "raven.core.webhooks",
        "raven.core.errors",
        "raven.core.migrations",
        "raven.core.design_tokens",
        "raven.core.canvas",
        "raven.core.self_heal",
        "raven.core.jobs",
        "raven.core.circuit_breaker",
        # Core submodules
        "raven.core.monitor",
        "raven.core.monitor.engine",
        "raven.core.monitor.store",
        "raven.core.monitor.models",
        "raven.core.monitor.conditions",
        "raven.core.monitor.alert",
        "raven.core.monitor.checkers.http_check",
        "raven.core.monitor.checkers.price",
        "raven.core.monitor.checkers.rss",
        "raven.core.routine",
        "raven.core.routine.engine",
        "raven.core.routine.store",
        "raven.core.routine.models",
        "raven.core.task_engine",
        "raven.core.task_engine.planner",
        "raven.core.task_engine.runner",
        "raven.core.task_engine.store",
        "raven.core.task_engine.models",
        "raven.core.task_engine.tool_registry",
        "raven.core.coder",
        "raven.core.coder.session",
        "raven.core.coder.indexer",
        "raven.core.coder.review",
        "raven.core.coder.models",
        "raven.core.security",
        "raven.core.security.security_audit",
        "raven.core.security.context_filter",
        "raven.core.security.tool_policy",
        "raven.core.auth",
        "raven.core.auth.store",
        "raven.core.auth.tokens",
        "raven.core.rag",
        "raven.core.rag.vector",
        "raven.core.rag.chunker",
        "raven.core.rag.embeddings",
        # CLI
        "raven.cli",
        "raven.cli.main",
        "raven.cli.onboard",
        "raven.cli.service",
        "raven.cli.doctor",
        # All channels
        "raven.channels",
        "raven.channels.base",
        "raven.channels.enterprise_base",
        "raven.channels.telegram",
        "raven.channels.telegram.channel",
        "raven.channels.discord",
        "raven.channels.discord.channel",
        "raven.channels.webchat",
        "raven.channels.webchat.channel",
        "raven.channels.slack",
        "raven.channels.slack.channel",
        "raven.channels.whatsapp",
        "raven.channels.whatsapp.channel",
        "raven.channels.matrix",
        "raven.channels.matrix.channel",
        "raven.channels.googlechat",
        "raven.channels.googlechat.channel",
        "raven.channels.signal",
        "raven.channels.signal.channel",
        "raven.channels.irc",
        "raven.channels.irc.channel",
        "raven.channels.teams",
        "raven.channels.teams.channel",
        "raven.channels.feishu",
        "raven.channels.feishu.channel",
        "raven.channels.line",
        "raven.channels.line.channel",
        # Plugins
        "raven.plugins.memory",
        "raven.plugins.memory.plugin",
        "raven.plugins.browser",
        "raven.plugins.browser.plugin",
        "raven.plugins.cron",
        "raven.plugins.cron.plugin",
        "raven.plugins.code",
        "raven.plugins.code.plugin",
        "raven.plugins.files",
        "raven.plugins.files.plugin",
        "raven.plugins.api",
        "raven.plugins.api.plugin",
        "raven.plugins.ocr",
        "raven.plugins.ocr.plugin",
        "raven.plugins.process",
        "raven.plugins.process.plugin",
        "raven.plugins.git",
        "raven.plugins.git.plugin",
        "raven.plugins.sessions",
        "raven.plugins.sessions.plugin",
        # Tools (task engine tools)
        "raven.tools",
        "raven.tools.register_all",
        "raven.tools.http",
        "raven.tools.file",
        "raven.tools.shell",
        "raven.tools.browser",
        "raven.tools.utils",
        "raven.tools.process",
        "raven.tools.notify",
        "raven.tools.db",
        "raven.tools.env",
        # Monitors (checker implementations)
        "raven.monitors",
        "raven.monitors.register_all",
        "raven.monitors.http",
        "raven.monitors.price",
        "raven.monitors.rss",
        "raven.monitors.file",
        "raven.monitors.process",
        # Routines (routine implementations)
        "raven.routines",
        "raven.routines.register_all",
        "raven.routines.briefing",
        "raven.routines.file_watch",
        # Voice
        "raven.voice",
        "raven.voice.stt",
        "raven.voice.tts",
        # TUI
        "raven.tui",
        "raven.tui.app",
        # AI-OS-MVP bridge
        "aios",
        "aios.api",
        "aios.api.bridge",
        "aios.agents",
        "aios.agents.orchestrator",
        "aios.runtime",
        "aios.runtime.adapter",
        # Third-party hidden imports
        "pkg_resources",
        "pkgutil",
        "asyncio",
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http.auto",
        "uvicorn.middleware",
        "uvicorn.middleware.wsgi",
        "fastapi",
        "fastapi.routing",
        "websockets",
        "websockets.legacy",
        "httpx",
        "aiosqlite",
        "pydantic",
        "pydantic_settings",
        "click",
        "rich",
        "rich.markdown",
        "rich.table",
        "rich.panel",
        "loguru",
        "apscheduler",
        "apscheduler.triggers",
        "apscheduler.triggers.cron",
        "chromadb",
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "sympy",
        "PIL",
        "cv2",
        "torch",
        "tensorflow",
        "notebook",
        "jupyter",
        "ipython",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="raven",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    icon=None,
)
