"""Landing page invariant: what site/index.html claims must match the code.

``site/tools-data.js`` and ``site/mcp-frames.js`` are generated by
``scripts/record_site_frames.py`` from a live ``raven-mcp`` process, while the page also
hand-writes counts (tool count, version, hero preview, adapter count) and embeds request
frames in its preset buttons. These tests compare those statements with the generated data
and with the tool registry itself, so a renamed tool, a version bump, an unrecorded button
or a stray file in ``site/`` fails CI instead of shipping a wrong claim.

The last group pins how the site is published instead: MkDocs must not build into ``site/``,
exactly one workflow may hand a tree to GitHub Pages, that workflow installs a pinned theme,
the documentation loads no font from a third-party host, and the MkDocs palette is the
repository's purple-black brand (not Material's default indigo). The first two were violated
at once when the docs workflow uploaded ``site`` after ``mkdocs build`` had overwritten it,
and the live root served documentation with every landing asset 404.

The narrow-viewport guard checks a chain that spans three files: the toggle button, the
panel rules in the ``max-width: 900px`` query and the handler in ``main.js``. Half of it
looking finished is what left the last nav link scrolled out of sight behind a hidden
scrollbar on a phone.
"""

from __future__ import annotations

import importlib.util
import json
import re
import tomllib
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, cast

import yaml

from raven.core.mcp.server import _to_mcp_tool
from ravencode.runtime.tools import get_tool_definitions

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
INDEX = SITE / "index.html"
STYLES = SITE / "styles.css"
MAIN_JS = SITE / "main.js"
TOOLS_DATA = SITE / "tools-data.js"
FRAMES_DATA = SITE / "mcp-frames.js"
GENERATOR = ROOT / "scripts" / "record_site_frames.py"
MKDOCS_YML = ROOT / "mkdocs.yml"
WORKFLOWS = ROOT / ".github" / "workflows"
DEPLOY_SITE = WORKFLOWS / "deploy-site.yml"

PUBLISHED_URL = "https://ssrjkk.github.io/raven/"
FIRST_PARTY = ("https://ssrjkk.github.io/", "https://github.com/ssrjkk/raven")

# The landing page describes the protocol, not the products that speak it.
CLIENT_NAMES = ("qoder", "cursor", "windsurf", "cline", "opencode", "claude")

HERO_TOOL_LIST = re.compile(r'\{"jsonrpc":"2\.0","id":\d+,"result":\{"tools":\[.*?\]\}\}')
CHANNEL_COUNT = re.compile(
    r'<dt class="spec-term">Channel adapters</dt>\s*<dd class="spec-value">(\d+)</dd>'
)
CSS_URL = re.compile(r"url\('([^']+)'\)")
NAV_TOGGLE = re.compile(
    r'<button class="nav-toggle"[^>]*aria-expanded="false"[^>]*aria-controls="([^"]+)"'
)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def brand_token(name: str) -> str:
    """One color token from the landing page's ``:root`` block, the project's only palette."""
    match = re.search(
        rf"^\s*--{re.escape(name)}: (#[0-9a-f]{{6}});", read(STYLES), re.MULTILINE
    )
    assert match is not None, name
    return match.group(1)


class _AssetParser(HTMLParser):
    """``HTMLParser`` lowercases tag and attribute names, so ``<SCRIPT SRC=...>`` is
    caught like the lowercase form; a tag regex is not."""

    def __init__(self) -> None:
        super().__init__()
        self.urls: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag not in {"link", "script"}:
            return
        self.urls += [value for name, value in attrs if name in {"href", "src"} and value]


def external_asset_urls(path: Path) -> list[str]:
    parser = _AssetParser()
    parser.feed(read(path))
    return [url for url in parser.urls if url.startswith(("http://", "https://"))]


def local_refs() -> set[str]:
    """Every first-party file the page or its stylesheet asks the browser to fetch."""
    html = read(INDEX) + read(SITE / "404.html")
    refs = {
        name
        for name in re.findall(r'(?:src|href)="([^"?#]+)"', html)
        if not name.startswith(("http://", "https://", "mailto:"))
    }
    refs |= {
        name
        for name in CSS_URL.findall(read(STYLES))
        if not name.startswith(("http://", "https://", "data:"))
    }
    return refs


def parse_js(name: str, path: Path) -> Any:
    """Read the JSON literal a generated ``const <name> = ...;``` file assigns."""
    body = read(path).split(f"const {name} = ", 1)[1]
    end = max(body.rindex("]"), body.rindex("}"))
    return json.loads(body[: end + 1])


def tools_data() -> list[dict[str, Any]]:
    return cast("list[dict[str, Any]]", parse_js("TOOLS_DATA", TOOLS_DATA))


def frames() -> list[dict[str, Any]]:
    payload = cast("dict[str, Any]", parse_js("MCP_FRAMES", FRAMES_DATA))
    return cast("list[dict[str, Any]]", payload["frames"])


def registry_tools() -> list[dict[str, Any]]:
    """The list the stdio server returns for ``tools/list``, in registry order."""
    return [_to_mcp_tool(defn) for defn in get_tool_definitions()]


def build_entries() -> Any:
    spec = importlib.util.spec_from_file_location("record_site_frames", GENERATOR)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {GENERATOR}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.build_entries


def signature(frame: dict[str, Any]) -> str:
    """Request identity as the browser computes it: method + params, ids ignored."""
    return json.dumps(
        [frame["method"], frame.get("params", {})], sort_keys=True, separators=(",", ":")
    )


def project_version() -> str:
    pyproject = tomllib.loads(read(ROOT / "pyproject.toml"))
    return cast(str, pyproject["project"]["version"])


def test_tools_data_is_what_the_registry_reports() -> None:
    assert tools_data() == build_entries()(registry_tools())


def test_generated_files_carry_the_regeneration_banner() -> None:
    for path in (TOOLS_DATA, FRAMES_DATA):
        assert read(path).startswith("// Generated by scripts/record_site_frames.py"), path


def test_tool_count_statements_match_the_registry() -> None:
    total = len(registry_tools())
    html = read(INDEX)
    assert {int(n) for n in re.findall(r"(\d+) tools\b", html)} == {total}
    assert set(re.findall(r"data-tool-count>(\d+)</span>", html)) == {str(total)}


def test_hero_preview_matches_the_registry_order() -> None:
    match = HERO_TOOL_LIST.search(read(INDEX))
    assert match is not None
    listed = json.loads(match.group(0))["result"]["tools"]
    shown = [tool["name"] for tool in listed[:-1]]
    order = [tool["name"] for tool in registry_tools()]
    assert shown == order[: len(shown)]
    assert listed[-1] == f"… {len(order) - len(shown)} more"


def test_recorded_tools_list_is_current() -> None:
    listed = next(pair for pair in frames() if pair["request"]["method"] == "tools/list")
    recorded = [tool["name"] for tool in listed["response"]["result"]["tools"]]
    assert recorded == [tool["name"] for tool in registry_tools()]


def test_every_preset_button_has_a_recording() -> None:
    commands = re.findall(r"data-cmd='([^']+)'", read(INDEX))
    assert len(commands) == 8
    recorded = {signature(pair["request"]) for pair in frames()}
    for command in commands:
        assert signature(cast("dict[str, Any]", json.loads(command))) in recorded, command


def test_recorded_frames_are_valid_json_rpc() -> None:
    for pair in frames():
        request, response = pair["request"], pair["response"]
        assert request["jsonrpc"] == "2.0"
        assert isinstance(request.get("method"), str)
        if request["method"].startswith("notifications/"):
            assert "id" not in request
            assert response is None
            continue
        assert response is not None
        assert response["jsonrpc"] == "2.0"
        assert response["id"] == request["id"]
        assert ("result" in response) != ("error" in response)
        if "error" in response:
            assert response["error"]["code"] in (-32601, -32602)
            assert isinstance(response["error"]["message"], str)


def test_initialize_recording_agrees_with_the_server() -> None:
    pair = next(p for p in frames() if p["request"]["method"] == "initialize")
    result = pair["response"]["result"]
    assert result["protocolVersion"] == "2025-03-26"
    assert result["serverInfo"] == {"name": "raven-mcp", "version": project_version()}


def test_version_statements_agree_with_pyproject() -> None:
    assert {project_version()} == set(re.findall(r"\d+\.\d+\.\d+", read(INDEX)))


def test_channel_adapter_count_matches_the_tree() -> None:
    adapters = len(list((ROOT / "raven" / "channels").glob("*/channel.py")))
    match = CHANNEL_COUNT.search(read(INDEX))
    assert match is not None
    assert int(match.group(1)) == adapters


def test_local_assets_exist_and_nothing_in_site_is_unreferenced() -> None:
    refs = local_refs()
    for name in refs:
        assert (SITE / name).is_file(), f"{name} is referenced but missing"
    allowed = refs | {"robots.txt", "sitemap.xml", "404.html", "README.md", "og-image.png"}
    present = {p.relative_to(SITE).as_posix() for p in SITE.rglob("*") if p.is_file()}
    assert sorted(present - allowed) == []


def test_page_loads_no_third_party_asset() -> None:
    """Typography is self-hosted: every ``link``/``script`` request stays first-party.

    A third-party stylesheet would also hand the visitor's IP to another host, which a
    page advertising a self-hosted server should not do.
    """
    for path in (INDEX, SITE / "404.html"):
        for url in external_asset_urls(path):
            assert url.startswith(FIRST_PARTY), f"{path.name} loads {url}"
        assert "fonts.googleapis.com" not in read(path)
        assert "fonts.gstatic.com" not in read(path)


def test_faces_point_at_fonts_that_ship() -> None:
    css = read(STYLES)
    faces = re.findall(r"@font-face \{(.*?)\}", css, re.S)
    assert len(faces) >= 5
    for face in faces:
        family = re.search(r"font-family: '([^']+)'", face)
        src = re.search(r"url\('([^']+)'\)", face)
        assert family is not None and src is not None, face
        assert (SITE / src.group(1)).is_file(), src.group(1)
        assert "font-display: swap" in face
    used = {m.group(1) for f in faces if (m := re.search(r"font-family: '([^']+)'", f))}
    assert used == {"IBM Plex Mono", "IBM Plex Sans", "Space Grotesk"}


def media(width: int) -> str:
    """One ``@media (max-width: <width>px)`` block, up to its column-zero closing brace."""
    css = read(STYLES)
    block = css[css.index(f"@media (max-width: {width}px) {{") :]
    return block[: block.index("\n}") + 2]


def test_narrow_viewports_get_a_disclosure_menu() -> None:
    """Below 900px seven links do not fit beside the brand. Kept on one line they scrolled,
    and because the scrollbar is suppressed the last link left no trace that anything was
    there; wrapped, they stacked rows of links over the hero. The button, the panel and the
    handler are three files that have to name each other, so pin the whole chain."""
    html = read(INDEX)
    toggle = NAV_TOGGLE.search(html)
    assert toggle is not None
    assert f'<nav aria-label="Primary" id="{toggle.group(1)}">' in html

    mobile = media(900)
    assert ".js .nav-toggle {" in mobile
    assert ".js .navbar.nav-open > nav {" in mobile
    assert ".nav-links" not in media(560)

    js = read(MAIN_JS)
    for hook in ("nav-open", "aria-expanded", "matchMedia"):
        assert hook in js, hook


def test_seo_assets_point_at_the_published_url() -> None:
    assert f'<link rel="canonical" href="{PUBLISHED_URL}">' in read(INDEX)
    assert PUBLISHED_URL in read(SITE / "robots.txt")
    assert f"<loc>{PUBLISHED_URL}</loc>" in read(SITE / "sitemap.xml")
    assert '<meta name="robots" content="noindex">' in read(SITE / "404.html")
    assert f'<meta property="og:image" content="{PUBLISHED_URL}og-image.png">' in read(INDEX)
    assert (SITE / "og-image.png").is_file()


def test_landing_page_does_not_name_mcp_clients() -> None:
    text = (read(INDEX) + read(SITE / "404.html") + read(SITE / "README.md")).lower()
    for name in CLIENT_NAMES:
        assert name not in text, name


def mkdocs_config() -> dict[str, Any]:
    return cast("dict[str, Any]", yaml.safe_load(read(MKDOCS_YML)))


def pages_upload_paths() -> set[tuple[str, str]]:
    """``(workflow, artifact path)`` for every job that hands a tree to GitHub Pages."""
    uploads: set[tuple[str, str]] = set()
    for workflow in sorted(WORKFLOWS.glob("*.yml")):
        for job in (yaml.safe_load(read(workflow)) or {}).get("jobs", {}).values():
            for step in job.get("steps") or []:
                if str(step.get("uses", "")).startswith("actions/upload-pages-artifact"):
                    uploads.add((workflow.name, step["with"]["path"]))
    return uploads


def test_docs_build_writes_outside_the_landing_dir() -> None:
    site_dir = (ROOT / mkdocs_config()["site_dir"]).resolve()
    assert not site_dir.is_relative_to(SITE.resolve()), f"mkdocs would overwrite {SITE}"


def test_docs_are_published_where_the_artifact_puts_them() -> None:
    """The publisher copies the docs output to ``<artifact>/docs``, so the output directory
    name and ``site_url`` have to agree or every link in the documentation 404s."""
    config = mkdocs_config()
    assert Path(str(config["site_dir"])).name == "docs"
    assert config["site_url"] == f"{PUBLISHED_URL}docs/"


def test_exactly_one_workflow_publishes_pages() -> None:
    """Two publishers of one Pages root is how the landing page disappeared: whichever
    workflow ran last won, and the loser's files 404'd."""
    assert pages_upload_paths() == {("deploy-site.yml", "build/pages")}


def test_documentation_loads_no_third_party_font() -> None:
    """Material fetches Roboto from Google Fonts unless the theme says otherwise, and a
    product that advertises a server you run yourself should not hand every visitor's IP
    address to Google on the documentation side either."""
    assert mkdocs_config()["theme"].get("font") is False
    assert "fonts.googleapis.com" not in read(MKDOCS_YML)
    for page in sorted((ROOT / "docs").rglob("*.md")):
        assert "fonts.googleapis.com" not in read(page), page


def test_documentation_carries_the_brand_palette() -> None:
    """Material's public build resolves only its own named colors in ``theme.palette`` — a hex
    is written to the page as a data attribute with no matching rule, and the theme falls back
    to its default indigo. The brand scheme is overridden by a stylesheet instead, and that
    stylesheet has to be listed at the top level: an ``extra_css`` key inside ``theme:`` reaches
    only a legacy template global the theme ignores, which copied the file into the build
    without any page ever linking it.

    The palette values are read from the landing page's ``:root`` block so the two surfaces
    cannot drift apart."""
    config = mkdocs_config()
    assert "extra_css" not in config["theme"]
    sheets = config["extra_css"]
    assert sheets == ["stylesheets/brand.css"]
    css = read(ROOT / "docs" / sheets[0])
    assert f"--md-primary-fg-color: {brand_token('bg')};" in css
    assert f"--md-typeset-a-color: {brand_token('violet-deep')};" in css


def test_documentation_build_is_pinned() -> None:
    """The publisher installs the theme itself, so an unpinned requirement lets an upstream
    release change the published documentation without any commit here."""
    steps = yaml.safe_load(read(DEPLOY_SITE))["jobs"]["deploy"]["steps"]
    install = next(step for step in steps if "mkdocs-material" in str(step.get("run", "")))
    assert "mkdocs-material==" in install["run"]
    assert "mkdocstrings[python]==" in install["run"]
