// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Chunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Document       *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreDocumentRequest) Reset() {
	*x = StoreDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDocumentRequest) ProtoMessage() {}

func (x *StoreDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDocumentRequest.ProtoReflect.Descriptor instead.
func (*StoreDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *StoreDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *StoreDocumentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type StoreDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDocumentResponse) Reset() {
	*x = StoreDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDocumentResponse) ProtoMessage() {}

func (x *StoreDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDocumentResponse.ProtoReflect.Descriptor instead.
func (*StoreDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *StoreDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *StoreDocumentResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type SearchSimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Filter        map[string]string      `protobuf:"bytes,3,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarRequest) Reset() {
	*x = SearchSimilarRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarRequest) ProtoMessage() {}

func (x *SearchSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarRequest.ProtoReflect.Descriptor instead.
func (*SearchSimilarRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSimilarRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSimilarRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchSimilarRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchSimilarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	QueryTimeMs   float32                `protobuf:"fixed32,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarResponse) Reset() {
	*x = SearchSimilarResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarResponse) ProtoMessage() {}

func (x *SearchSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarResponse.ProtoReflect.Descriptor instead.
func (*SearchSimilarResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSimilarResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SearchSimilarResponse) GetQueryTimeMs() float32 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type GetConversationContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationContextRequest) Reset() {
	*x = GetConversationContextRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationContextRequest) ProtoMessage() {}

func (x *GetConversationContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationContextRequest.ProtoReflect.Descriptor instead.
func (*GetConversationContextRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetConversationContextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ContextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     float32                `protobuf:"fixed32,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextMessage) Reset() {
	*x = ContextMessage{}
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextMessage) ProtoMessage() {}

func (x *ContextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextMessage.ProtoReflect.Descriptor instead.
func (*ContextMessage) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *ContextMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ContextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContextMessage) GetTimestamp() float32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetConversationContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ContextMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationContextResponse) Reset() {
	*x = GetConversationContextResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationContextResponse) ProtoMessage() {}

func (x *GetConversationContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationContextResponse.ProtoReflect.Descriptor instead.
func (*GetConversationContextResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{8}
}

func (x *GetConversationContextResponse) GetMessages() []*ContextMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type StoreMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMemoryRequest) Reset() {
	*x = StoreMemoryRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMemoryRequest) ProtoMessage() {}

func (x *StoreMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMemoryRequest.ProtoReflect.Descriptor instead.
func (*StoreMemoryRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{9}
}

func (x *StoreMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StoreMemoryRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StoreMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StoreMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMemoryResponse) Reset() {
	*x = StoreMemoryResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMemoryResponse) ProtoMessage() {}

func (x *StoreMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMemoryResponse.ProtoReflect.Descriptor instead.
func (*StoreMemoryResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{10}
}

func (x *StoreMemoryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDocumentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\"\xc5\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12:\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1e.rag.v1.Document.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x127\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1b.rag.v1.Chunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x14StoreDocumentRequest\x12,\n" +
	"\bdocument\x18\x01 \x01(\v2\x10.rag.v1.DocumentR\bdocument\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"Y\n" +
	"\x15StoreDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x05R\n" +
	"chunkCount\"\xb7\x01\n" +
	"\x14SearchSimilarRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\x12@\n" +
	"\x06filter\x18\x03 \x03(\v2(.rag.v1.SearchSimilarRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x15SearchSimilarResponse\x12%\n" +
	"\x06chunks\x18\x01 \x03(\v2\r.rag.v1.ChunkR\x06chunks\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x02R\vqueryTimeMs\"T\n" +
	"\x1dGetConversationContextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\\\n" +
	"\x0eContextMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x02R\ttimestamp\"T\n" +
	"\x1eGetConversationContextResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.rag.v1.ContextMessageR\bmessages\"a\n" +
	"\x12StoreMemoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"%\n" +
	"\x13StoreMemoryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"8\n" +
	"\x15DeleteDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"(\n" +
	"\x16DeleteDocumentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xaa\x03\n" +
	"\n" +
	"RAGService\x12L\n" +
	"\rStoreDocument\x12\x1c.rag.v1.StoreDocumentRequest\x1a\x1d.rag.v1.StoreDocumentResponse\x12L\n" +
	"\rSearchSimilar\x12\x1c.rag.v1.SearchSimilarRequest\x1a\x1d.rag.v1.SearchSimilarResponse\x12g\n" +
	"\x16GetConversationContext\x12%.rag.v1.GetConversationContextRequest\x1a&.rag.v1.GetConversationContextResponse\x12F\n" +
	"\vStoreMemory\x12\x1a.rag.v1.StoreMemoryRequest\x1a\x1b.rag.v1.StoreMemoryResponse\x12O\n" +
	"\x0eDeleteDocument\x12\x1d.rag.v1.DeleteDocumentRequest\x1a\x1e.rag.v1.DeleteDocumentResponseB5Z3github.com/ssrjkk/raven/services/proto/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rag_v1_rag_proto_goTypes = []any{
	(*Document)(nil),                       // 0: rag.v1.Document
	(*Chunk)(nil),                          // 1: rag.v1.Chunk
	(*StoreDocumentRequest)(nil),           // 2: rag.v1.StoreDocumentRequest
	(*StoreDocumentResponse)(nil),          // 3: rag.v1.StoreDocumentResponse
	(*SearchSimilarRequest)(nil),           // 4: rag.v1.SearchSimilarRequest
	(*SearchSimilarResponse)(nil),          // 5: rag.v1.SearchSimilarResponse
	(*GetConversationContextRequest)(nil),  // 6: rag.v1.GetConversationContextRequest
	(*ContextMessage)(nil),                 // 7: rag.v1.ContextMessage
	(*GetConversationContextResponse)(nil), // 8: rag.v1.GetConversationContextResponse
	(*StoreMemoryRequest)(nil),             // 9: rag.v1.StoreMemoryRequest
	(*StoreMemoryResponse)(nil),            // 10: rag.v1.StoreMemoryResponse
	(*DeleteDocumentRequest)(nil),          // 11: rag.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),         // 12: rag.v1.DeleteDocumentResponse
	nil,                                    // 13: rag.v1.Document.MetadataEntry
	nil,                                    // 14: rag.v1.Chunk.MetadataEntry
	nil,                                    // 15: rag.v1.SearchSimilarRequest.FilterEntry
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	13, // 0: rag.v1.Document.metadata:type_name -> rag.v1.Document.MetadataEntry
	14, // 1: rag.v1.Chunk.metadata:type_name -> rag.v1.Chunk.MetadataEntry
	0,  // 2: rag.v1.StoreDocumentRequest.document:type_name -> rag.v1.Document
	15, // 3: rag.v1.SearchSimilarRequest.filter:type_name -> rag.v1.SearchSimilarRequest.FilterEntry
	1,  // 4: rag.v1.SearchSimilarResponse.chunks:type_name -> rag.v1.Chunk
	7,  // 5: rag.v1.GetConversationContextResponse.messages:type_name -> rag.v1.ContextMessage
	2,  // 6: rag.v1.RAGService.StoreDocument:input_type -> rag.v1.StoreDocumentRequest
	4,  // 7: rag.v1.RAGService.SearchSimilar:input_type -> rag.v1.SearchSimilarRequest
	6,  // 8: rag.v1.RAGService.GetConversationContext:input_type -> rag.v1.GetConversationContextRequest
	9,  // 9: rag.v1.RAGService.StoreMemory:input_type -> rag.v1.StoreMemoryRequest
	11, // 10: rag.v1.RAGService.DeleteDocument:input_type -> rag.v1.DeleteDocumentRequest
	3,  // 11: rag.v1.RAGService.StoreDocument:output_type -> rag.v1.StoreDocumentResponse
	5,  // 12: rag.v1.RAGService.SearchSimilar:output_type -> rag.v1.SearchSimilarResponse
	8,  // 13: rag.v1.RAGService.GetConversationContext:output_type -> rag.v1.GetConversationContextResponse
	10, // 14: rag.v1.RAGService.StoreMemory:output_type -> rag.v1.StoreMemoryResponse
	12, // 15: rag.v1.RAGService.DeleteDocument:output_type -> rag.v1.DeleteDocumentResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
