from __future__ import annotations


class OutputLimits:
    TOOL_RESULT_PREVIEW = 200
    TOOL_RESULT_SHORT = 2_000
    TOOL_RESULT_FULL = 10_000
    TOOL_RESULT_LARGE = 20_000
    TOOL_RESULT_EXTRA = 30_000
    FILE_CONTENT_LIMIT = 50_000
    IMAGE_BYTES_LIMIT = 500_000
    GLOB_RESULT_LIMIT = 500
    GREP_RESULT_LIMIT = 200
    SEARCH_RESULT_LIMIT = 50
    GIT_STDERR_LIMIT = 5_000


class Timeouts:
    SHORT = 10
    MEDIUM = 30
    LONG = 120
    EXTENDED = 300
    DOCKER_HEALTH_MS = 5_000
    DOCKER_EXEC_MS = 30_000
    SANDBOX = 30
    GIT = 15
    FORMATTER = 30
    LSP_REQUEST = 30
    LLM = 120
    REGISTER_PLUGIN = 2.0


class Limits:
    MAX_STEPS_DEFAULT = 30
    MAX_STEPS_FAST = 50
    MAX_STEPS_AUTONOMOUS = 100
    MAX_TOOL_RETRIES = 3
    MAX_CONCURRENT_SUB_AGENTS = 3
    MAX_CONCURRENT_DAG = 5
    MAX_HOST_SOCKET_RETRIES = 3
    MAX_CHANNEL_PARTS = 2
    UNDO_STACK_SIZE = 100
    CACHE_MAX_SIZE = 256
    CACHE_TTL_SEC = 300.0
    TOKEN_ESTIMATION_DIVISOR = 4
    OUTPUT_TRUNCATE_LEN = 6
    EXP_BACKOFF_MAX_ATTEMPTS = 10


class Paths:
    CHECKPOINTS_DIR = "data/checkpoints"
    SESSIONS_DIR = "data/sessions"
    MEMORY_FILE = "data/ravencode_memory.json"
    AGENTS_MD = "AGENTS.md"
    RAVENCODE_CONFIG = "ravencode.json"
