from __future__ import annotations

import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from loguru import logger


@dataclass
class SeccompProfile:
    allow_read: bool = True
    allow_write: bool = True
    allow_network: bool = False
    allow_exec: bool = False
    allow_fs: bool = False
    extra_syscalls: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "allow_read": self.allow_read,
            "allow_write": self.allow_write,
            "allow_network": self.allow_network,
            "allow_exec": self.allow_exec,
            "allow_fs": self.allow_fs,
            "extra_syscalls": list(self.extra_syscalls),
        }


@dataclass
class CgroupConfig:
    memory_max_bytes: int = 512 * 1024 * 1024
    cpu_max_percent: float = 50.0
    pids_max: int = 64
    iops_max: int = 100

    def to_dict(self) -> dict[str, Any]:
        return {
            "memory_max_bytes": self.memory_max_bytes,
            "cpu_max_percent": self.cpu_max_percent,
            "pids_max": self.pids_max,
            "iops_max": self.iops_max,
        }


@dataclass
class NsJailConfig:
    enabled: bool = False
    chroot_dir: str = ""
    time_limit_seconds: int = 30
    max_procs: int = 4
    max_mem_mb: int = 512
    iface_no_lo: bool = False
    clone_newnet: bool = True
    clone_newipc: bool = True
    clone_newuts: bool = True
    clone_newpid: bool = True
    clone_newuser: bool = True
    mount_proc: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "enabled": self.enabled,
            "chroot_dir": self.chroot_dir,
            "time_limit_seconds": self.time_limit_seconds,
            "max_procs": self.max_procs,
            "max_mem_mb": self.max_mem_mb,
            "iface_no_lo": self.iface_no_lo,
            "clone_newnet": self.clone_newnet,
            "clone_newipc": self.clone_newipc,
            "clone_newuts": self.clone_newuts,
            "clone_newpid": self.clone_newpid,
            "clone_newuser": self.clone_newuser,
            "mount_proc": self.mount_proc,
        }

    def to_nsjail_cfg(self) -> str:
        lines = [
            "// nsjail config — auto-generated by Raven",
            f"time_limit: {self.time_limit_seconds}",
            f"max_procs: {self.max_procs}",
            f"max_mem: {self.max_mem_mb}",
            f"clone_newnet: {'true' if self.clone_newnet else 'false'}",
            f"clone_newipc: {'true' if self.clone_newipc else 'false'}",
            f"clone_newuts: {'true' if self.clone_newuts else 'false'}",
            f"clone_newpid: {'true' if self.clone_newpid else 'false'}",
            f"clone_newuser: {'true' if self.clone_newuser else 'false'}",
            f"mount_proc: {'true' if self.mount_proc else 'false'}",
        ]
        if self.chroot_dir:
            lines.append(f"chroot: {self.chroot_dir}")
        return "\n".join(lines)


def detect_seccomp() -> bool:
    if sys.platform == "win32":
        return False
    try:
        import seccomp
        seccomp.Arch  # type: ignore
        return True
    except ImportError:
        return False


def detect_nsjail() -> bool:
    return shutil.which("nsjail") is not None


def detect_cgroups_v2() -> bool:
    if sys.platform == "win32":
        return False
    cgroup_fs = Path("/sys/fs/cgroup")
    if cgroup_fs.is_dir():
        return (cgroup_fs / "cgroup.controllers").exists()
    return False


def get_available_sandboxes() -> dict[str, bool]:
    return {
        "subprocess": True,
        "docker": shutil.which("docker") is not None,
        "nsjail": detect_nsjail(),
        "seccomp": detect_seccomp(),
        "cgroups_v2": detect_cgroups_v2(),
    }


def recommended_profile() -> dict[str, Any]:
    avail = get_available_sandboxes()
    logger.info("Available sandbox backends: {}", avail)

    if avail["nsjail"]:
        cfg = NsJailConfig(enabled=True)
        return {"backend": "nsjail", "nsjail": cfg.to_dict(), "cgroup": CgroupConfig().to_dict()}

    if avail["docker"]:
        return {
            "backend": "docker",
            "image": "python:3.12-slim",
            "seccomp": SeccompProfile().to_dict(),
            "cgroup": CgroupConfig().to_dict(),
        }

    if avail["subprocess"]:
        return {
            "backend": "subprocess",
            "seccomp": SeccompProfile().to_dict() if avail["seccomp"] else None,
            "cgroup": CgroupConfig().to_dict() if avail["cgroups_v2"] else None,
        }

    return {"backend": "none", "note": "No sandbox backend available"}
