name: Proto Checks

on:
  pull_request:
    paths:
      - "services/proto/**/*.proto"
      - "services/proto/buf.yaml"
      - "services/proto/buf.gen.yaml"
  push:
    branches: [main, develop]
    paths:
      - "services/proto/**/*.proto"

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.32.2"

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "services/proto"

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "services/proto"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=refs/heads/main,subdir=services/proto"
